---

##################################################
# zabbix variables

zabbix:
  - name: zabbix-server
#    url: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
#    download_dir: /home/it/zabbix_download
    zabbix_nginx: /etc/opt/rh/rh-nginx116/nginx/conf.d
    zabbiix_php-fpm72: /etc/opt/rh/rh-php72/php-fpm.d
    zabbix_repos: /etc/yum.repos.d
    user: zabbix
    group: zabbix
    state: present
    mode: '0644'
#    release: zabbix-release-5.0-1.el5.noarch.rpm
#    conf_path: /etc/zabbix/
#    gpgcheck: 0
#    description:  Zabbix Official Repository - $basearch

zabbix_packages:
  - zabbix-server-mysql
  - zabbix-agent2
  - centos-release-scl

zabbix_centos_packages:
  - epel-release
  - yum-utils
  - rh-php72-php-fpm
  - zabbix-web-mysql-scl
  - zabbix-nginx-conf-scl

zabbix_services:
  - zabbix-server
  - rh-nginx116-nginx
  - rh-php72-php-fpm
  - zabbix-agent2


##################################################
# Firewall variables

firewall:
  ports:
    - 888/tcp
    - 10051/tcp
    - 2049/tcp
    - 80/tcp
    - 111/tcp
    - 2048/tcp
    - 8080/tcp
    - 8443/tcp
    - 17088/tcp
    - 17089/tcp
    - 17090/tcp
    - 17091/tcp
    - 17092/tcp
    - 9000/tcp

  services:
    - http
    - https
    - dhcp
    - dns

  rules:
    - rule protocol value="ospf" accept
    - rule protocol value="icmp" accept

##################################################
# mariadb variables

mariadb_packages:
  - MySQL-python
  - mariadb
  - mariadb-server


# Databases.
mysql_databases:
   - name: zabbix
     collation: utf8_general_ci
     encoding: utf8
     replicate: 1
     state: present

# Users.
mysql_users:
   - name: zabbix
     host: 127.0.0.1
     password: zabbix
     priv: '*.*:ALL,GRANT'
     state: present

##################################################
# nginx variables

nginx:
  - name: nginx
    root_dir: /usr/share/nginx/html
    conf_dir: /etc/nginx

##################################################
# php-fpm variables

php_fpm:
  packages:
    - php
    - php-cli
    - php-fpm
    - php-json
    - php-pdo
    - php-mysqlnd
    - php-zip
    - php-gd
    - php-mbstring
    - php-curl
    - php-xml
    - php-pear
    - php-bcmath
    - MySQL-python

