---

- name: install and start php-fpm
  block:
    - name: install {{ zabbix_centos_packages }}
      yum:
        name: "{{ item }}"
        update_cache: yes
        state: present
      loop: "{{ zabbix_centos_packages }}"

