---

- name: Create DB for Zabbix
  block:
    - name: Create DB {{ mysql_databases.name }} for Zabbix
      mysql_db:
        name: "{{ item.name }}"
        state: "{{ item.state | default('present') }}"
        encoding: "{{ item.encoding | default('utf8') }}"
        collation: "{{ item.collation | default('utf8_general_ci') }}"
      loop: "{{ mysql_databases }}"