---

- name: install and start mariadb-server
  block:
    - name: install mariadb-server
      yum:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop: "{{ mariadb_packages }}"

    - name: start mariadb-server
      service:
        name: mariadb
        state: started
        enabled: yes


