---

- name: Populate service facts
  service_facts:

- name: start firewall if firewalld.service is stopped
  service:
    name: firewalld
    state: started
  when: ansible_facts.services['firewalld.service'].state == 'stopped'